using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.940
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyConfigurationAttribute("dev")]
[assembly: AssemblyCompanyAttribute("http://ndoc.sourceforge.net")]
[assembly: AssemblyProductAttribute("NDoc")]
[assembly: AssemblyCopyrightAttribute("")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("1.3.*")]
[assembly: AssemblyInformationalVersionAttribute("1.3")]

